title: "Kévin Massat"
description: "Portfolio de Kévin Massat, chargé de communication à Toulouse."
baseurl: "/portfolio-kevin-massat"
url: "https://kmassat.github.io"

# Collections
collections:
  experiences:
    output: true
    permalink: /:name/

# Valeurs par défaut
defaults:
  - scope:
      path: ""
      type: "experiences"
    values:
      layout: "experience"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Exclusions
exclude:
  - README.md
  - cloudcannon.config.yml
