title: Kévin Massat — Chargé de Communication

collections:
  realisations:
    output: false
  experiences:
    output: true
    permalink: /:slug.html # Magique : génère la page à la racine exacte de votre site !
