title: Kévin Massat — Chargé de Communication
# Configuration pour autoriser les collections du CMS
collections:
  realisations:
    output: false # false car ce sont des cartes sur la page d'accueil, pas des pages isolées
