backend:
  name: git-gateway
  branch: main # Mettez 'master' si votre branche principale sur GitHub s'appelle master

media_folder: "images" # Dossier où le CMS va stocker les images que vous envoyez
public_folder: "/images" # Lien utilisé dans le HTML pour afficher les images

collections:
  - name: "pages"
    label: "Pages"
    folder: "pages" # Dossier où seront sauvegardées vos nouvelles pages
    create: true # Autorise la création de nouvelles pages !
    slug: "{{slug}}" # L'URL sera générée d'après le titre
    fields:
      - { label: "Titre de la page", name: "title", widget: "string" }
      - { label: "Image principale", name: "image", widget: "image", required: false }
      - { label: "Contenu / Texte", name: "body", widget: "markdown" }
